### PR TITLE
Update Flextop to 9f66dac

### LINKED ISSUE #39: PWAs and shortcuts are associated with the main browser window
Hi!

After granting chrome access to ~/.local/share/applications and ~/.local/share/icons, adding shortcuts to PWAs and other websites they are still associated with the launcher to chrome, meaning they are all grouped under the main window:

Skärmbild från 2021-03-04 11-09-05

Checking the WM_CLASSes, they seem to be the set correctly compared to the "regular" version of chrome and are the same for both:
Browser: `WM_CLASS(STRING) = "google-chrome", "Google-chrome"`
YouTube PWA: `WM_CLASS(STRING) = "crx_agimnkijcaahngcdmfeangaknmldooml", "Google-chrome"`

Comparing the desktop files, nothing really stands out.
Flatpak:
> #!/usr/bin/env xdg-open
>
>[Desktop Entry]
>Version=1.0
>Terminal=false
>Type=Application
>Name=YouTube
>Exec='flatpak' 'run' '--branch=beta' '--arch=x86_64' '--command=/app/bin/chrome' 'com.google.Chrome' '--profile-directory=Default' '--app-id=agimnkijcaahngcdmfeangaknmldooml'
>Icon=flatpak-com-google-Chrome-chrome-agimnkijcaahngcdmfeangaknmldooml-Default
>StartupWMClass=crx_agimnkijcaahngcdmfeangaknmldooml

Regular chrome:
>#!/usr/bin/env xdg-open
>[Desktop Entry]
>Version=1.0
>Terminal=false
>Type=Application
>Name=YouTube
>Exec=/usr/bin/google-chrome-stable --profile-directory=Default --app-id=agimnkijcaahngcdmfeangaknmldooml
>Icon=chrome-agimnkijcaahngcdmfeangaknmldooml-Default
>StartupWMClass=crx_agimnkijcaahngcdmfeangaknmldooml

The icons also doesn't show up properly in the launcher:
Skärmbild från 2021-03-04 11-05-59

### PR DESCRIPTION
**Pull request by refi64**
This should fix #39. @ludvigng @pedrofleck please test.

### CODE REVIEW

**Comment by ludvigng** [comment]
Did a quick test with installing the browser and then installing the youtube pwa. Seems to work fine!

**Comment by pedrofleck** [comment]
I installed the build and now I can't create PWAs, I'm getting this 
Captura de tela de 2021-04-08 00-25-40 error even though I've ran `sudo flatpak override --filesystem=~/.local/share/applications --filesystem=~/.local/share/icons com.google.Chrome`.

**Comment by refi64** [comment]
Well...that's weird, the updated commits don't actually touch the code that detects that. Could you run it with `flatpak run --env=G_MESSAGES_DEBUG=all com.google.Chrome` and post the output?

**Comment by pedrofleck** [comment]
Sure, here it is:
```
[pedrofleck@thinkpad-fedora ~]$ flatpak run --env=G_MESSAGES_DEBUG=all com.google.Chrome
[2 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/extra/chrome --type=zygote
Stub sandbox ignoring command: /app/extra/nacl_helper
[2:2:0408/235401.275981:ERROR:nacl_fork_delegate_linux.cc(329)] Bad NaCl helper startup ack (0 bytes)
(chrome:2): Gdk-DEBUG: 23:54:01.590: Ignoring portal setting for org.gnome.desktop.interface toolkit-accessibility
(chrome:2): Gdk-DEBUG: 23:54:01.590: Ignoring portal setting for org.gnome.desktop.interface gtk-color-palette
(chrome:2): Gdk-DEBUG: 23:54:01.590: Ignoring portal setting for org.gnome.desktop.interface can-change-accels
(chrome:2): Gdk-DEBUG: 23:54:01.590: Using portal setting for org.gnome.desktop.interface enable-animations: true

(chrome:2): Gdk-DEBUG: 23:54:01.590: Using portal setting for org.gnome.desktop.interface cursor-blink: true

(chrome:2): Gdk-DEBUG: 23:54:01.590: Ignoring portal setting for org.gnome.desktop.interface clock-show-weekday
(chrome:2): Gdk-DEBUG: 23:54:01.590: Using portal setting for org.gnome.desktop.interface icon-theme: 'Adwaita'

(chrome:2): Gdk-DEBUG: 23:54:01.590: Ignoring portal setting for org.gnome.desktop.interface gtk-im-preedit-style
(chrome:2): Gdk-DEBUG: 23:54:01.590: Ignoring portal setting for org.gnome.desktop.interface scaling-factor
(chrome:2): Gdk-DEBUG: 23:54:01.590: Ignoring portal setting for org.gnome.desktop.interface menus-have-tearoff
(chrome:2): Gdk-DEBUG: 23:54:01.590: Using portal setting for org.gnome.desktop.interface cursor-size: 24

(chrome:2): Gdk-DEBUG: 23:54:01.590: Ignoring portal setting for org.gnome.desktop.interface gtk-color-scheme
(chrome:2): Gdk-DEBUG: 23:54:01.590: Using portal setting for org.gnome.desktop.interface gtk-im-module: 'gtk-im-context-simple'

(chrome:2): Gdk-DEBUG: 23:54:01.590: Ignoring portal setting for org.gnome.desktop.interface gtk-timeout-initial
(chrome:2): Gdk-DEBUG: 23:54:01.590: Using portal setting for org.gnome.desktop.interface gtk-theme: 'Adwaita-dark'

(chrome:2): Gdk-DEBUG: 23:54:01.590: Ignoring portal setting for org.gnome.desktop.interface clock-show-seconds
(chrome:2): Gdk-DEBUG: 23:54:01.590: Ignoring portal setting for org.gnome.desktop.interface clock-show-date
(chrome:2): Gdk-DEBUG: 23:54:01.590: Using portal setting for org.gnome.desktop.interface cursor-blink-time: 1200

(chrome:2): Gdk-DEBUG: 23:54:01.590: Ignoring portal setting for org.gnome.desktop.interface toolbar-icons-size
(chrome:2): Gdk-DEBUG: 23:54:01.590: Using portal setting for org.gnome.desktop.interface font-antialiasing: 'grayscale'

(chrome:2): Gdk-DEBUG: 23:54:01.590: Ignoring portal setting for org.gnome.desktop.interface gtk-timeout-repeat
(chrome:2): Gdk-DEBUG: 23:54:01.590: Ignoring portal setting for org.gnome.desktop.interface toolbar-style
(chrome:2): Gdk-DEBUG: 23:54:01.590: Ignoring portal setting for org.gnome.desktop.interface monospace-font-name
(chrome:2): Gdk-DEBUG: 23:54:01.590: Ignoring portal setting for org.gnome.desktop.interface enable-hot-corners
(chrome:2): Gdk-DEBUG: 23:54:01.590: Using portal setting for org.gnome.desktop.interface overlay-scrolling: true

(chrome:2): Gdk-DEBUG: 23:54:01.590: Using portal setting for org.gnome.desktop.interface cursor-blink-timeout: 10

(chrome:2): Gdk-DEBUG: 23:54:01.590: Using portal setting for org.gnome.desktop.interface gtk-key-theme: 'Default'

(chrome:2): Gdk-DEBUG: 23:54:01.590: Ignoring portal setting for org.gnome.desktop.interface toolbar-detachable
(chrome:2): Gdk-DEBUG: 23:54:01.590: Using portal setting for org.gnome.desktop.interface cursor-theme: 'Adwaita'

(chrome:2): Gdk-DEBUG: 23:54:01.590: Ignoring portal setting for org.gnome.desktop.interface avatar-directories
(chrome:2): Gdk-DEBUG: 23:54:01.590: Ignoring portal setting for org.gnome.desktop.interface gtk-im-status-style
(chrome:2): Gdk-DEBUG: 23:54:01.590: Ignoring portal setting for org.gnome.desktop.interface menubar-detachable
(chrome:2): Gdk-DEBUG: 23:54:01.590: Using portal setting for org.gnome.desktop.interface text-scaling-factor: 1.0

(chrome:2): Gdk-DEBUG: 23:54:01.590: Ignoring portal setting for org.gnome.desktop.interface show-battery-percentage
(chrome:2): Gdk-DEBUG: 23:54:01.590: Ignoring portal setting for org.gnome.desktop.interface clock-format
(chrome:2): Gdk-DEBUG: 23:54:01.590: Ignoring portal setting for org.gnome.desktop.interface document-font-name
(chrome:2): Gdk-DEBUG: 23:54:01.590: Using portal setting for org.gnome.desktop.interface font-rgba-order: 'rgb'

(chrome:2): Gdk-DEBUG: 23:54:01.590: Using portal setting for org.gnome.desktop.interface font-hinting: 'slight'

(chrome:2): Gdk-DEBUG: 23:54:01.590: Ignoring portal setting for org.gnome.desktop.interface menubar-accel
(chrome:2): Gdk-DEBUG: 23:54:01.590: Using portal setting for org.gnome.desktop.interface gtk-enable-primary-paste: true

(chrome:2): Gdk-DEBUG: 23:54:01.590: Ignoring portal setting for org.gnome.desktop.interface locate-pointer
(chrome:2): Gdk-DEBUG: 23:54:01.590: Using portal setting for org.gnome.desktop.interface font-name: 'Google Sans 11'

(chrome:2): Gdk-DEBUG: 23:54:01.590: Using portal setting for org.gnome.desktop.sound theme-name: '__custom'

(chrome:2): Gdk-DEBUG: 23:54:01.590: Using portal setting for org.gnome.desktop.sound event-sounds: true

(chrome:2): Gdk-DEBUG: 23:54:01.590: Using portal setting for org.gnome.desktop.sound input-feedback-sounds: false

(chrome:2): Gdk-DEBUG: 23:54:01.590: Ignoring portal setting for org.gnome.desktop.sound allow-volume-above-100-percent
(chrome:2): Gdk-DEBUG: 23:54:01.590: Ignoring portal setting for org.gnome.settings-daemon.plugins.xsettings overrides
(chrome:2): Gdk-DEBUG: 23:54:01.590: Ignoring portal setting for org.gnome.settings-daemon.plugins.xsettings disabled-gtk-modules
(chrome:2): Gdk-DEBUG: 23:54:01.590: Ignoring portal setting for org.gnome.settings-daemon.plugins.xsettings enabled-gtk-modules
(chrome:2): Gdk-DEBUG: 23:54:01.590: Ignoring portal setting for org.gnome.desktop.a11y always-show-universal-access-status
(chrome:2): Gdk-DEBUG: 23:54:01.590: Using portal setting for org.gnome.desktop.a11y always-show-text-caret: false

(chrome:2): Gdk-DEBUG: 23:54:01.590: Ignoring portal setting for org.gnome.desktop.input-sources mru-sources
(chrome:2): Gdk-DEBUG: 23:54:01.590: Ignoring portal setting for org.gnome.desktop.input-sources show-all-sources
(chrome:2): Gdk-DEBUG: 23:54:01.590: Ignoring portal setting for org.gnome.desktop.input-sources current
(chrome:2): Gdk-DEBUG: 23:54:01.590: Ignoring portal setting for org.gnome.desktop.input-sources xkb-options
(chrome:2): Gdk-DEBUG: 23:54:01.590: Ignoring portal setting for org.gnome.desktop.input-sources sources
(chrome:2): Gdk-DEBUG: 23:54:01.590: Ignoring portal setting for org.gnome.desktop.input-sources per-window
(chrome:2): Gdk-DEBUG: 23:54:01.590: Ignoring portal setting for org.gnome.desktop.privacy disable-microphone
(chrome:2): Gdk-DEBUG: 23:54:01.590: Ignoring portal setting for org.gnome.desktop.privacy hide-identity
(chrome:2): Gdk-DEBUG: 23:54:01.590: Using portal setting for org.gnome.desktop.privacy recent-files-max-age: -1

(chrome:2): Gdk-DEBUG: 23:54:01.590: Ignoring portal setting for org.gnome.desktop.privacy remove-old-temp-files
(chrome:2): Gdk-DEBUG: 23:54:01.590: Ignoring portal setting for org.gnome.desktop.privacy usb-protection-level
(chrome:2): Gdk-DEBUG: 23:54:01.590: Ignoring portal setting for org.gnome.desktop.privacy old-files-age
(chrome:2): Gdk-DEBUG: 23:54:01.590: Ignoring portal setting for org.gnome.desktop.privacy disable-sound-output
(chrome:2): Gdk-DEBUG: 23:54:01.590: Ignoring portal setting for org.gnome.desktop.privacy remember-app-usage
(chrome:2): Gdk-DEBUG: 23:54:01.591: Ignoring portal setting for org.gnome.desktop.privacy disable-camera
(chrome:2): Gdk-DEBUG: 23:54:01.591: Using portal setting for org.gnome.desktop.privacy remember-recent-files: true

(chrome:2): Gdk-DEBUG: 23:54:01.591: Ignoring portal setting for org.gnome.desktop.privacy report-technical-problems
(chrome:2): Gdk-DEBUG: 23:54:01.591: Ignoring portal setting for org.gnome.desktop.privacy remove-old-trash-files
(chrome:2): Gdk-DEBUG: 23:54:01.591: Ignoring portal setting for org.gnome.desktop.privacy send-software-usage-stats
(chrome:2): Gdk-DEBUG: 23:54:01.591: Ignoring portal setting for org.gnome.desktop.privacy show-full-name-in-top-bar
(chrome:2): Gdk-DEBUG: 23:54:01.591: Ignoring portal setting for org.gnome.desktop.privacy usb-protection
(chrome:2): Gdk-DEBUG: 23:54:01.591: Ignoring portal setting for org.gnome.desktop.wm.preferences theme
(chrome:2): Gdk-DEBUG: 23:54:01.591: Ignoring portal setting for org.gnome.desktop.wm.preferences focus-new-windows
(chrome:2): Gdk-DEBUG: 23:54:01.591: Ignoring portal setting for org.gnome.desktop.wm.preferences num-workspaces
(chrome:2): Gdk-DEBUG: 23:54:01.591: Ignoring portal setting for org.gnome.desktop.wm.preferences raise-on-click
(chrome:2): Gdk-DEBUG: 23:54:01.591: Ignoring portal setting for org.gnome.desktop.wm.preferences disable-workarounds
(chrome:2): Gdk-DEBUG: 23:54:01.591: Ignoring portal setting for org.gnome.desktop.wm.preferences titlebar-uses-system-font
(chrome:2): Gdk-DEBUG: 23:54:01.591: Ignoring portal setting for org.gnome.desktop.wm.preferences titlebar-font
(chrome:2): Gdk-DEBUG: 23:54:01.591: Ignoring portal setting for org.gnome.desktop.wm.preferences resize-with-right-button
(chrome:2): Gdk-DEBUG: 23:54:01.591: Using portal setting for org.gnome.desktop.wm.preferences action-right-click-titlebar: 'menu'

(chrome:2): Gdk-DEBUG: 23:54:01.591: Using portal setting for org.gnome.desktop.wm.preferences action-middle-click-titlebar: 'none'

(chrome:2): Gdk-DEBUG: 23:54:01.591: Ignoring portal setting for org.gnome.desktop.wm.preferences mouse-button-modifier
(chrome:2): Gdk-DEBUG: 23:54:01.591: Ignoring portal setting for org.gnome.desktop.wm.preferences auto-raise
(chrome:2): Gdk-DEBUG: 23:54:01.591: Ignoring portal setting for org.gnome.desktop.wm.preferences workspace-names
(chrome:2): Gdk-DEBUG: 23:54:01.591: Using portal setting for org.gnome.desktop.wm.preferences action-double-click-titlebar: 'toggle-maximize'

(chrome:2): Gdk-DEBUG: 23:54:01.591: Ignoring portal setting for org.gnome.desktop.wm.preferences visual-bell-type
(chrome:2): Gdk-DEBUG: 23:54:01.591: Ignoring portal setting for org.gnome.desktop.wm.preferences focus-mode
(chrome:2): Gdk-DEBUG: 23:54:01.591: Using portal setting for org.gnome.desktop.wm.preferences button-layout: 'appmenu:close'

(chrome:2): Gdk-DEBUG: 23:54:01.591: Ignoring portal setting for org.gnome.desktop.wm.preferences auto-raise-delay
(chrome:2): Gdk-DEBUG: 23:54:01.591: Ignoring portal setting for org.gnome.desktop.wm.preferences audible-bell
(chrome:2): Gdk-DEBUG: 23:54:01.591: Ignoring portal setting for org.gnome.desktop.wm.preferences visual-bell
(chrome:2): Gdk-DEBUG: 23:54:01.591: Using portal setting for org.gnome.fontconfig serial: 0

(chrome:2): GLib-DEBUG: 23:54:01.606: unsetenv() is not thread-safe and should not be used after threads are created
(chrome:2): GLib-GIO-DEBUG: 23:54:01.610: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
(chrome:2): GLib-GIO-DEBUG: 23:54:01.677: _g_io_module_get_default: Found default implementation keyfile (GKeyfileSettingsBackend) for ‘gsettings-backend’
[2:37:0408/235401.750278:ERROR:nacl_browser.cc(290)] Failed to open NaCl IRT file "/app/extra/nacl_irt_x86_64.nexe": -4
[52:52:0408/235401.750687:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
[2:2:0408/235401.768680:ERROR:wayland_surface.cc(59)] Server doesn't support zwp_linux_explicit_synchronization_v1.
```

By the way, I'm running it with the following flags, but the same issue happens without them:
`
--enable-features=UseOzonePlatform,VaapiVideoDecoder
--ozone-platform=wayland
--use-gl=egl
--ignore-gpu-blocklist
--enable-gpu-rasterization
--enable-zero-copy
--enable-accelerated-video-decode
`

Also, I'm not sure now if this is related to this build, I've noticed now that the flatpak version inherited the webapps from my default Chrome installation and there is a chance that the first webapp that I tried to create earlier was successful because it already existed, now I've tried with a new one.

**Comment by refi64** [comment]
@pedrofleck ah apologies, I did a major goof: when you run it with that command, you also need to attempt to install a PWA and let the dialog box appear. Sorry for any wasted time resulting from that!

**Comment by refi64** [comment]
No reply, I'm guessing this is an unrelated flextop issue or bugfix, so merged by hand.

**Pull request closed without merging**
