### PR TITLE
Update Chrome to 88.0.4324.182

### PR DESCRIPTION
**Pull request by cho2**

### CODE REVIEW

**Comment by cho2** [comment]
```
fatal: unable to access 'https://gitlab.freedesktop.org/pipewire/pipewire.git/': gnutls_handshake() failed: Error in the pull function.
```

**Comment by cho2** [comment]
Chromium also failed https://github.com/flathub/org.chromium.Chromium/pull/67#issuecomment-780220414

**Comment by refi64** [comment]
So uhh I didn't notice and also pushed the update once again 😅 (around the same time or so), no idea what the issue is but the git command is working here locally...

As a workaround I've just switched to the PipeWire GitHub mirror for now.

**Comment by cho2** [comment]
Thanks!

**Pull request closed without merging**
