### PR TITLE
Expose the widevine directory into the sandbox

### LINKED ISSUE #212: DRM issue Streaming platforms
Currently i have issues on streaming platforms.(Netflix, HBO, Spotify, amazon, ...)

Other people have the same issue here:
https://support.google.com/chrome/thread/216603047/drm-widevine-issue-on-chrome-update-playback-of-protected-content-is-not-enabled?hl=en

image

image

image

My info:
OS: SteamOS Holo x86_64 
Host: Jupiter 1
Kernel: 5.13.0-valve36-1-neptune
Chrome: Version 113.0.5672.126 (Official Build) unknown (64-bit)

### PR DESCRIPTION
**Pull request by refi64**
Potentially fixes #212, #213.

@lordvault @ramonmoraes8080 could you try this and see if it fixes anything, or the log output changes?

### CODE REVIEW

**Comment by ramonmoraes8080** [comment]
@refi64 that actually worked! ty.

**Comment by lordvault** [comment]
I still getting an error.

>[2:2:0529/155751.816098:ERROR:nacl_browser.cc(288)] Failed to open NaCl IRT file "/app/extra/nacl_irt_x86_64.nexe": -4
[498:298:0529/155757.892012:ERROR:cdm_module.cc(114)] CDM at /home/deck/.var/app/com.google.Chrome/config/google-chrome/WidevineCdm/4.10.2652.1/_platform_specific/linux_x64/libwidevinecdm.so could not be loaded.
[498:298:0529/155757.892138:ERROR:cdm_module.cc(115)] Error: 
/home/deck/.var/app/com.google.Chrome/config/google-chrome/WidevineCdm/4.10.2652.1/_platform_specific/linux_x64/libwidevinecdm.so: cannot open shared object file: Operation not permitted
Fontconfig error: Cannot load default config file: No such file: (null)

image

**Comment by GlenKPeterson** [comment]
```
$ flatpak install --user https://dl.flathub.org/build-repo/26240/com.google.Chrome.flatpakref

error: Can't load uri https://dl.flathub.org/build-repo/26240/com.google.Chrome.flatpakref: Server returned status 404: Not Found
```

**Comment by refi64** [comment]
Didn't actually fix anything.

**Pull request closed without merging**
