### PR TITLE
bump Platform and base app to 24.08

### PR DESCRIPTION
**Pull request by xanscale**
anyone can test it and comment if it works or not ?

https://github.com/flathub/com.google.Chrome/issues/333

### CODE REVIEW

**Comment by Bohne13** [comment]
> anyone can test it and comment if it works or not ?
> 
> #333

Sadly I don't have a test environment, and don't want to test on my "production" systems.

But im really interested in, if it works!

**Review by Bohne13 — APPROVED** [review]
This code change looks fine to me.

Writing this actually from a tab within the testbuild (as far as I can tell).

Didn't noticed any difference in it's behavior!

**Comment by xanscale** [comment]
@refi64 ping

**Comment by refi64** [comment]
thanks!

**Pull request merged**
