### PR TITLE
fix tray icon on kde wayland

### PR DESCRIPTION
**Pull request by Etaash-mathamsetty**

### CODE REVIEW

**Comment by refi64** [comment]
Okay so I see the full picture now like the comments in the Discord Canary PR mention, but it appears that I was slow enough for the fix to already be in the latest stable :sweat_smile: any chance for a confirmation there?

**Comment by Etaash-mathamsetty** [comment]
@refi64 unfortunately, we still need to expose the entire org.kde.* for some reason, it might need other stuff along with org.kde.StatusNotifierItem-2-1

**Comment by Etaash-mathamsetty** [comment]
ok I managed to fix it, I will push the changes here soon

**Comment by Etaash-mathamsetty** [comment]
Seems like flathub has an error check for this (preventing you from setting the perms this way), that's interesting

**Comment by Etaash-mathamsetty** [comment]
I think I found a way to fix it

**Comment by Etaash-mathamsetty** [comment]
@refi64 works well :)

**Pull request merged**
