### PR TITLE
#69 User certificates save when closing Chrome

### PR DESCRIPTION
**Pull request by AlexGluck**

### CODE REVIEW

**Comment by tinywrkb** [comment]
I think that `--filesystem=~/.pki:create` would be better because the `--persist` option is half broken, as it doesn't handle well symlinks (say you put it in your dotfiles repo), and also the user can't override it.  
There's a special place in hell for applications that create dotfiles and dotfolders in the user's home, but seeing the non-optimal persistent folders support in Flatpak, creating `~/.pki` is the lesser evil.

**Comment by AlexGluck** [comment]
Thanks for good comment. In my case company require add their CA chains with client certificate for authentication, but i don't trust pki infrastructure my company. I use other containered (flatpak) browser for work with company services. I don't want share pki with sandboxed browser.
How i need do in that case?

I know both case need. For good solution, we can replace `persist` to suggested, but add some notice for change behavior required for me and some other users.

**Comment by tinywrkb** [comment]
> I don't want share pki with sandboxed browser.
> How i need do in that case?

This should do it

```
$ flatpak override --user --nofilesystem=~/.pki --persist=.pki com.google.Chrome
```

> I know both case need. For good solution, we can replace persist to suggested, but add some notice for change behavior required for me and some other users.

You can add a `README.md` and document this, but as this affects multiple apps, maybe documentation should be in [org.chromium.Chromium.BaseApp](https://github.com/flathub/org.chromium.Chromium.BaseApp), and a `README.md` here should point to the Chromium BaseApp.  
If it's being documented, then it mIght be a good idea to also link to [the upstream ticket](https://bugs.chromium.org/p/chromium/issues/detail?id=1038587).

**Comment by violetmage** [comment]
I agree with @tinywrkb; `--filesystem=~/.pki:create` is the lesser of the two evils.

The upstream ticket and associated PR seem kind of dead now, unfortunately.

**Comment by AlexGluck** [comment]
Just if somebody need this feature, she already described here.

**Pull request closed without merging**
