### PR TITLE
update icon as svg

### PR DESCRIPTION
**Pull request by xanscale**

### CODE REVIEW

**Comment by xanscale** [comment]
@refi64 @bbhtt

**Comment by refi64** [comment]
Where's the SVG file from?

**Comment by xanscale** [comment]
> Where's the SVG file from?

https://www.google.com/chrome/static/images/chrome-logo.svg

**Comment by Bohne13** [comment]
Have tried to find an official Google site for downloading the icons, but it seems Google doesn't provide something like that.

**Comment by xanscale** [comment]
> Have tried to find an official Google site for downloading the icons, but it seems Google doesn't provide something like that.

there is a problem using icon get from chrome homepage?
this is the same used by wikipedia https://en.wikipedia.org/wiki/Google_Chrome

**Comment by Bohne13** [comment]
> > Have tried to find an official Google site for downloading the icons, but it seems Google doesn't provide something like that.
> 
> there is a problem using icon get from chrome homepage? this is the same used by wikipedia https://en.wikipedia.org/wiki/Google_Chrome

No, there is no problem that I'm aware off. 
Would have been nice to use an official link/website, 
but using the SVG from the Google Chrome page or Wikipedia is also completely fine.

**Comment by xanscale** [comment]
@refi64 what do you think ?

**Pull request merged**
